// AUTO-GENERATED by scripts/build-content.ts from content/lens-copy.md.
// Do not hand-edit — edit the markdown source and re-run `bun run content:build`.

export const heroCopy = {
  "recruiter": "Nine years across five industries. Most recently I owned the entire AI product suite at a recruitment platform serving 150+ recruiters and 2,500+ client companies — 140% more work per recruiter, hiring ~25% faster. I've also shipped two AI products solo, outside any job, both live right now.",
  "operator": "Nine years across fintech, HR tech, marketplaces, mobility and regulated banking. At TopHire I owned the whole B2B AI suite reporting to the CEO — four products, sequenced by where recruiter time was actually going, and by the end I was the solo PM with 3-4 engineers. I also build the systems myself: two live production AI products, shipped solo, outside any employer.",
  "engineer": "**AI Product Manager who writes the backend.** Two live systems, built solo: a Retell voice agent made loop-proof by structure — the commitment ladder has no upward transition, so a declined ask can't be re-offered — and a governance assistant whose post-generation check drops any claim its source doesn't support. Same move both times: when an instruction can drift, replace it with a structure that can't."
} as const;
