// AUTO-GENERATED by scripts/build-content.ts from knowledge-book/ + content/*.md.
// Do not hand-edit — edit the markdown sources and re-run `bun run content:build`.

import type { Metric } from './types';

export const metrics: { projectSlug: string; metric: Metric }[] = [
  {
    "projectSlug": "automjet",
    "metric": {
      "label": "Connect rate",
      "value": "~70%",
      "method": "Live production funnel, ~500 calls/month",
      "sourceLabel": "instrumented"
    }
  },
  {
    "projectSlug": "automjet",
    "metric": {
      "label": "Full-conversation completion",
      "value": "~40%",
      "method": "Live production funnel",
      "sourceLabel": "instrumented"
    }
  },
  {
    "projectSlug": "automjet",
    "metric": {
      "label": "Terminal-node conversion (test ride / meeting / warm lead)",
      "value": "~20%",
      "method": "Live production funnel",
      "sourceLabel": "instrumented"
    }
  },
  {
    "projectSlug": "automjet",
    "metric": {
      "label": "Classified cold",
      "value": "~20%",
      "method": "Live production funnel",
      "sourceLabel": "instrumented",
      "caveat": "Classification is a read outcome, not a failure — the fourth funnel state, not a disclaimer."
    }
  },
  {
    "projectSlug": "grounded-governance",
    "metric": {
      "label": "Retrieval gate (GDPR slice)",
      "value": "7/7",
      "method": "Direct-lookup + adversarial retrieval eval",
      "sourceLabel": "instrumented"
    }
  },
  {
    "projectSlug": "grounded-governance",
    "metric": {
      "label": "Groundedness (first full run)",
      "value": "93.3% vs 95% target",
      "method": "24-item GDPR gate, interim Sonnet-5 generation config",
      "sourceLabel": "disclosed-gap",
      "caveat": "Interim config, not the final comprehensive re-run; certifies the interim setup only."
    }
  },
  {
    "projectSlug": "grounded-governance",
    "metric": {
      "label": "Correct-refusal (first full run)",
      "value": "83.3% vs 90% target",
      "method": "24-item GDPR gate, interim Sonnet-5 generation config",
      "sourceLabel": "disclosed-gap",
      "caveat": "Interim config, not the final comprehensive re-run."
    }
  },
  {
    "projectSlug": "grounded-governance",
    "metric": {
      "label": "Citation accuracy (first full run)",
      "value": "93.8% vs 90% target",
      "method": "24-item GDPR gate, interim Sonnet-5 generation config",
      "sourceLabel": "directional",
      "caveat": "Passed, but still an interim-config number."
    }
  },
  {
    "projectSlug": "grounded-governance",
    "metric": {
      "label": "Corpus",
      "value": "630 parents / 1,573 chunks, 5 frameworks",
      "method": "Deterministic parse to native hierarchy, one immutable snapshot",
      "sourceLabel": "instrumented"
    }
  },
  {
    "projectSlug": "voice-screening",
    "metric": {
      "label": "Call-completion, tech junior/mid",
      "value": "~60%",
      "method": "Segment-tested through a 1→5 client phased rollout, vs. ~60% human baseline",
      "sourceLabel": "instrumented"
    }
  },
  {
    "projectSlug": "voice-screening",
    "metric": {
      "label": "Call-completion, senior roles",
      "value": "Low 40s%",
      "method": "Same phased rollout",
      "sourceLabel": "disclosed-gap",
      "caveat": "Below the ~60% human-parity bar; not shipped for this segment."
    }
  },
  {
    "projectSlug": "voice-screening",
    "metric": {
      "label": "Cost per candidate",
      "value": "~₹30",
      "method": "~₹9/min × ~3 min average call",
      "sourceLabel": "instrumented"
    }
  },
  {
    "projectSlug": "voice-screening",
    "metric": {
      "label": "Recruiter time saved",
      "value": "~2 hrs/day",
      "method": "Measured against a 3-4 hrs/day target",
      "sourceLabel": "disclosed-gap",
      "caveat": "Below the original 3-4 hr/day target; reported as measured, not rounded up."
    }
  },
  {
    "projectSlug": "resume-shortlisting",
    "metric": {
      "label": "Shortlisting rate",
      "value": "35% → 42%",
      "method": "A/B test, 5 jobs, ~400 candidates",
      "sourceLabel": "instrumented"
    }
  },
  {
    "projectSlug": "resume-shortlisting",
    "metric": {
      "label": "Adoption",
      "value": "80%+",
      "method": "Platform-wide usage",
      "sourceLabel": "instrumented"
    }
  },
  {
    "projectSlug": "drip-campaign",
    "metric": {
      "label": "Positive reply rate",
      "value": "~20% → ~+30%",
      "method": "Online A/B tied to reply-rate tracking",
      "sourceLabel": "instrumented"
    }
  },
  {
    "projectSlug": "drip-campaign",
    "metric": {
      "label": "Recruiter time saved",
      "value": "~8 hrs/week",
      "method": "3-month post-launch survey mirroring a pre-launch baseline",
      "sourceLabel": "directional",
      "caveat": "Survey-based, not instrumented."
    }
  },
  {
    "projectSlug": "drip-campaign",
    "metric": {
      "label": "Adoption",
      "value": "90%+",
      "method": "Platform-wide usage",
      "sourceLabel": "instrumented"
    }
  },
  {
    "projectSlug": "lending",
    "metric": {
      "label": "Retailers on in-app credit",
      "value": "6,000+",
      "method": "Platform scale at end of tenure",
      "sourceLabel": "instrumented"
    }
  },
  {
    "projectSlug": "lending",
    "metric": {
      "label": "MTU lift, credit cohort",
      "value": "32%",
      "method": "Credit cohort vs. non-credit retailers",
      "sourceLabel": "instrumented"
    }
  },
  {
    "projectSlug": "lending",
    "metric": {
      "label": "Overdue rate",
      "value": "~6%",
      "method": "Reported alongside growth metrics, not the period’s optimization target",
      "sourceLabel": "disclosed-gap",
      "caveat": "Not optimized for in this period; disclosed rather than omitted."
    }
  },
  {
    "projectSlug": "cashback-builder",
    "metric": {
      "label": "Month-1 retention",
      "value": "28% → 40%",
      "method": "Cohort before/after comparison, exposed to the loop vs. not",
      "sourceLabel": "instrumented"
    }
  },
  {
    "projectSlug": "cashback-builder",
    "metric": {
      "label": "Points-based transaction volume",
      "value": "$1M+/month",
      "method": "Ongoing tracking at scale",
      "sourceLabel": "instrumented"
    }
  },
  {
    "projectSlug": "cashback-builder",
    "metric": {
      "label": "AOV contribution",
      "value": "Directional",
      "method": "Plausible mechanism, not isolated from other AOV drivers",
      "sourceLabel": "directional",
      "caveat": "Not precisely isolated from nurture.farm’s other AOV drivers over the same period."
    }
  },
  {
    "projectSlug": "pii-waterfall",
    "metric": {
      "label": "Operational savings",
      "value": "$100k/year",
      "method": "Cost-per-successful-lookup, before vs. after the waterfall",
      "sourceLabel": "instrumented"
    }
  },
  {
    "projectSlug": "pii-waterfall",
    "metric": {
      "label": "Segment configurations",
      "value": "3 (India-tech, India-non-tech, US)",
      "method": "Provider set + field requirements per segment",
      "sourceLabel": "instrumented"
    }
  },
  {
    "projectSlug": "seller-payouts",
    "metric": {
      "label": "On-time payment rate",
      "value": "99%",
      "method": "RBI-compliant payout automation across 6 payment modes",
      "sourceLabel": "instrumented"
    }
  },
  {
    "projectSlug": "checkout-optimization",
    "metric": {
      "label": "Checkout friction",
      "value": "Reduced",
      "method": "A/B tests across payment-mode ordering, amount UI, address flow",
      "sourceLabel": "directional"
    }
  },
  {
    "projectSlug": "support-chatbot",
    "metric": {
      "label": "Queries handled end to end",
      "value": "~40%",
      "method": "Slack + Gmail ingestion, fine-tuned on real Q&A",
      "sourceLabel": "instrumented"
    }
  },
  {
    "projectSlug": "ola-billing",
    "metric": {
      "label": "Billing disputes cut",
      "value": "$200k/year",
      "method": "Decision-tree fare-prediction model, top 5 cities",
      "sourceLabel": "instrumented"
    }
  },
  {
    "projectSlug": "ola-billing",
    "metric": {
      "label": "Bill accuracy",
      "value": "91% → ~99%",
      "method": "Billing workflow simulation + compliance fix coordination",
      "sourceLabel": "instrumented"
    }
  },
  {
    "projectSlug": "early-career",
    "metric": {
      "label": "AML transactions flagged/month",
      "value": "10,000+",
      "method": "UK bank client, ~40% accuracy",
      "sourceLabel": "directional"
    }
  },
  {
    "projectSlug": "early-career",
    "metric": {
      "label": "Dealership PAT lift",
      "value": "~6 pts",
      "method": "Prashaste business evaluations, 6 dealerships, implemented directly",
      "sourceLabel": "instrumented"
    }
  }
];
