// AUTO-GENERATED by scripts/build-content.ts from knowledge-book/ + content/*.md.
// Do not hand-edit — edit the markdown sources and re-run `bun run content:build`.

import type { Principle } from './types';

export const principles: Principle[] = [
  {
    "slug": "chase-the-bottleneck",
    "num": 1,
    "group": "before-i-build",
    "title": "Chase the bottleneck",
    "body": "Sequenced by where time was actually going next, not a fixed roadmap written upfront. At TopHire the four AI products were never one simultaneous suite; each one addressed whatever bottleneck the last fix had just exposed.",
    "evidence": [
      {
        "projectSlug": "voice-screening",
        "note": "Explicitly framed as the next project because outreach was already automated and screening was now the largest time sink."
      },
      {
        "projectSlug": "drip-campaign",
        "note": "Addressed the outreach bottleneck that, once cleared, made screening the next visible drain on recruiter time."
      }
    ]
  },
  {
    "slug": "discovery-first",
    "num": 2,
    "group": "before-i-build",
    "title": "Discovery, before building",
    "body": "Talk to the people doing the work, or the people the product is for, before building. Real interviews and on-ground visits, not desk research, surface the actual friction a feature should address.",
    "evidence": [
      {
        "projectSlug": "lending",
        "note": "Retailer interviews and on-ground visits surfaced that offline sellers’ credit was the reason retailers weren’t buying through the app."
      },
      {
        "projectSlug": "cashback-builder",
        "note": "The same field research separately surfaced that price was retailers’ primary purchase-deciding factor."
      },
      {
        "projectSlug": "drip-campaign",
        "note": "Recruiter interviews plus a dedicated 50-candidate email-quality test, before the prompt work started."
      }
    ]
  },
  {
    "slug": "vendor-choice-is-an-experiment",
    "num": 3,
    "group": "how-i-decide",
    "title": "Vendor choice is an experiment",
    "body": "Every build-vs-buy or model choice ran as a measured comparison, not a default pick. Five documented bake-offs, spanning AI models and plain infrastructure vendors alike.",
    "evidence": [
      {
        "projectSlug": "voice-screening",
        "note": "Four voice vendors evaluated (ElevenLabs, Bolna, Retell AI, Gnani) before shipping on Retell AI."
      },
      {
        "projectSlug": "resume-shortlisting",
        "note": "GPT, Claude, and DeepSeek bake-off across input formats and prompt designs; Claude won."
      },
      {
        "projectSlug": "pii-waterfall",
        "note": "WhatsApp (AiSensy/Wati/Gupshup) and cloud calling (MyOperator/Servetel/Exotel) vendor bake-offs run the same period."
      }
    ]
  },
  {
    "slug": "cost-against-a-stated-bar",
    "num": 4,
    "group": "how-i-decide",
    "title": "Cost against a stated bar",
    "body": "A cost figure means nothing judged in isolation. Every cost decision is measured against a specific, stated outcome bar decided in advance, and the real result is reported against that bar even when it falls short.",
    "evidence": [
      {
        "projectSlug": "voice-screening",
        "note": "₹30/candidate was only worth it if it freed 3-4 hrs/day of recruiter time; the measured result was ~2 hrs/day, reported as the real number."
      },
      {
        "projectSlug": "pii-waterfall",
        "note": "Vendor spend re-sequenced by cost-and-need rather than picking a single cheaper vendor, saving $100k/year at the workflow-design level."
      }
    ]
  },
  {
    "slug": "phased-rollout",
    "num": 5,
    "group": "how-i-ship",
    "title": "Phased rollout",
    "body": "1 client/recruiter, then 5, then 10, then all, with 2-3 weeks at each stage to observe and fix issues before expanding. The shape maps onto the real org structure it launches into, not an arbitrary headcount split.",
    "evidence": [
      {
        "projectSlug": "voice-screening",
        "note": "Phased 1→5 rollout used to segment-test tech junior/mid/non-tech/senior before scoping down to two segments."
      },
      {
        "projectSlug": "drip-campaign",
        "note": "Same 1→5→10 rollout shape for both V1 and V2, 2-3 weeks per stage."
      }
    ]
  },
  {
    "slug": "north-star-plus-guardrail",
    "num": 6,
    "group": "how-i-ship",
    "title": "North star plus guardrail",
    "body": "A single headline number is never the whole story. Every shipped metric is paired with an explicit guardrail, tracked specifically so a win on the primary number couldn’t hide a regression underneath it.",
    "evidence": [
      {
        "projectSlug": "resume-shortlisting",
        "note": "35%→42% shortlisting rate shipped with 1st-interview % tracked as the explicit guardrail."
      },
      {
        "projectSlug": "drip-campaign",
        "note": "Positive reply rate as the north star; bounce rate and complaint rate as the guardrails."
      }
    ]
  },
  {
    "slug": "real-demo-not-a-deck",
    "num": 7,
    "group": "what-i-trust",
    "title": "A real demo, not a deck",
    "body": "A running artifact is the approval gate, not a slide deck or a script mockup. The same instinct shows up again outside any employer: both personal products are shared as live, running systems.",
    "evidence": [
      {
        "projectSlug": "voice-screening",
        "note": "Leadership sign-off came from real generated call recordings played live, not a deck."
      },
      {
        "projectSlug": "automjet",
        "note": "Shared as a live production system taking real calls, not a screenshot or a slide."
      },
      {
        "projectSlug": "grounded-governance",
        "note": "Shared as a live, public URL with an in-product evaluation page showing its own measured quality."
      }
    ]
  },
  {
    "slug": "deterministic-not-inferred",
    "num": 8,
    "group": "what-i-trust",
    "title": "Deterministic, not inferred",
    "body": "Wherever a system needs to record what happened, the design reads the actual, deterministic result rather than inferring or guessing one after the fact.",
    "evidence": [
      {
        "projectSlug": "automjet",
        "note": "`call_status` is read directly off the ending node the conversation actually reached, never inferred from sentiment or keywords."
      },
      {
        "projectSlug": "grounded-governance",
        "note": "A post-generation entailment check verifies every claim against its cited source; the model is never trusted to vouch for its own grounding."
      },
      {
        "projectSlug": "voice-screening",
        "note": "Low-confidence extractions route to human review rather than guessing at an answer and shipping it silently."
      }
    ]
  }
];
