/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkGroundedGovernanceRouteImport } from './routes/work/grounded-governance'
import { Route as WorkAutomjetRouteImport } from './routes/work/automjet'
import { Route as CaseSlugRouteImport } from './routes/case/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkGroundedGovernanceRoute = WorkGroundedGovernanceRouteImport.update({
  id: '/work/grounded-governance',
  path: '/work/grounded-governance',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkAutomjetRoute = WorkAutomjetRouteImport.update({
  id: '/work/automjet',
  path: '/work/automjet',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseSlugRoute = CaseSlugRouteImport.update({
  id: '/case/$slug',
  path: '/case/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/case/$slug': typeof CaseSlugRoute
  '/work/automjet': typeof WorkAutomjetRoute
  '/work/grounded-governance': typeof WorkGroundedGovernanceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/case/$slug': typeof CaseSlugRoute
  '/work/automjet': typeof WorkAutomjetRoute
  '/work/grounded-governance': typeof WorkGroundedGovernanceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/case/$slug': typeof CaseSlugRoute
  '/work/automjet': typeof WorkAutomjetRoute
  '/work/grounded-governance': typeof WorkGroundedGovernanceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/case/$slug'
    | '/work/automjet'
    | '/work/grounded-governance'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/case/$slug' | '/work/automjet' | '/work/grounded-governance'
  id:
    | '__root__'
    | '/'
    | '/case/$slug'
    | '/work/automjet'
    | '/work/grounded-governance'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaseSlugRoute: typeof CaseSlugRoute
  WorkAutomjetRoute: typeof WorkAutomjetRoute
  WorkGroundedGovernanceRoute: typeof WorkGroundedGovernanceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/grounded-governance': {
      id: '/work/grounded-governance'
      path: '/work/grounded-governance'
      fullPath: '/work/grounded-governance'
      preLoaderRoute: typeof WorkGroundedGovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/automjet': {
      id: '/work/automjet'
      path: '/work/automjet'
      fullPath: '/work/automjet'
      preLoaderRoute: typeof WorkAutomjetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case/$slug': {
      id: '/case/$slug'
      path: '/case/$slug'
      fullPath: '/case/$slug'
      preLoaderRoute: typeof CaseSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaseSlugRoute: CaseSlugRoute,
  WorkAutomjetRoute: WorkAutomjetRoute,
  WorkGroundedGovernanceRoute: WorkGroundedGovernanceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
